services:
  app:
    container_name: taskmanager_app
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "${APP_HTTP_PORT:-8080}:80"  

    environment:
     
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development} 
      - ASPNETCORE_URLS=http://+:80;
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING} 
      - ADMIN_EMAIL=${ADMIN_EMAIL}                 
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}           

    volumes:
      - ./app_logs:/app/logs 
     
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: taskmanager_db
    image: postgres:15 
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin@example.com} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SuperTajneHasloDocker123!} 
      POSTGRES_DB: ${POSTGRES_DB:-TaskManagerDb} 
    ports:
      - "${DB_PORT:-5433}:5432"
    healthcheck: 

      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-taskmanager_user} -d $${POSTGRES_DB:-taskmanager_docker_db} -q"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 


